const filterData = {
  continent: [
    "Africa: Sub-Saharan",
    "Asia",
    "Australia & South Pacific",
    "Europe",
    "North America",
    "South America & Antarctica",
  ],
  setting: [
    "Beach",
    "City",
    "Countryside",
    "Cruise",
    "Desert",
    "Island",
    "Safari",
    "Town Or Village",
    "Water",
    "Wilderness",
    "Wine Region",
  ],
  theme: [
    "Adventure & Sport",
    "Art & Design",
    "Body, Mind & Soul",
    "Culture & History",
    "Entertainment",
    "Food & Drink",
    "Planes, Trains, Boats & Cars",
    "Safari",
    "Science & Nature",
    "Shopping",
  ],
  whenAvailable: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  bestTime: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  whoFor: [
    "Best Friends",
    "Couples",
    "Families (Old Kids)",
    "Families (Young Kids)",
    "Groups",
    "Over 60s",
    "Singles",
    "Under 30s",
  ],
  priceGuide: ["1", "2", "3", "4", "5"],
  priceGuideExp: ["Free", "1-10", "11-20", "21-30", "31-50", "50+"],
  greatFor: ["Ages 0-3", "Ages 4-7", "Ages 8-12", "Ages 13-18", "Ages 18+"],
  experienceType: ["Attraction", "Activity", "Festival or Event", "Tour"],
  attractionType: [
    "Art gallery",
    "Landmark",
    "Monument",
    "Museum",
    "Park",
    "Theme park or Fair",
    "Zoo or Aquarium",
    "Other",
  ],
  activityType: [
    "Adrenaline",
    "Caving",
    "Cycling",
    "Diving",
    "Fishing & Crabbing",
    "Hiking",
    "Hot air ballooning",
    "Kayaking",
    "Motor fun",
    "Sailing & Boating",
    "Ski & Snowboard",
    "Snorkel & Swim",
    "Walking",
    "White water rafting",
    "Other",
  ],
  eventType: ["International", "National", "Regional", "Local"],
  standard: ["Budget", "Luxury", "Mid-Range", "Super Lux"],
  starRating: ["1", "2", "3", "4", "5"],
  accommodationType: [
    "Apartment",
    "Guesthouse",
    "Hotel",
    "Private House",
    "Safari Camp",
  ],
  roomType: [
    "Bedrooms",
    "Cabins",
    "Cottages",
    "Suites",
    "Tent",
    "Treehouses",
    "Villas",
  ],
  hotelFacility: [
    "Creche",
    "Fitness Centre",
    "Fitness Classes",
    "Hot Tub",
    "Jacuzzi",
    "Kids Club",
    "Spa",
    "Spa Treatments",
    "Tennis Courts",
    "Yoga",
  ],
  roomFacility: [
    "Acccessible Room",
    "Air Conditioning",
    "Flat Screen TV",
    "Jacuzzi (Private)",
    "Pool (Private)",
    "Tea & Coffee Making Facilities",
    "WiFi",
  ],
  forFamilies: [
    "Connecting Rooms",
    "Family Rooms",
    "Rollaway Beds",
    "Sectionable Suites",
  ],
  skiFacilities: ["Shuttle To Slopes", "Ski In Ski Out", "Ski Rentals Onsite"],
  brand: [
    "Mandarin Oriental",
    "Marriott",
    "Ritz-Carlton",
    "Room Mate",
    "Sir Hotels",
  ],
};
export default filterData;
